name: Build and Push Docker Image & Redeploy to Cloud Run (Low-Cost, Internal Only)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: smooth-command-462303-n7     # <--- Your GCP Project ID here
      REGION: us-central1                 # <--- Your Artifact Registry region
      REPOSITORY: test-repo
      IMAGE_NAME: compute-worker
      IMAGE_TAG: latest
      REPO_NAME: test-repo
      IMAGE_NAME: compute-worker
      SERVICE_NAME: compute-operations
      SERVICE_ACCOUNT_MAIL: compute-operations-sa@smooth-command-462303-n7.iam.gserviceaccount.com
      VPC_CONNECTOR: cloudrun-connector


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_BOOTSTRAP_SA_KEY }}'

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t pubsub-fastapi .

      - name: Tag Docker image for Artifact Registry
        run: |
          docker tag pubsub-fastapi ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Cloud Run (low-cost, internal only)
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME \
            --region=$REGION \
            --platform=managed \
            --no-allow-unauthenticated \
            --vpc-connector=$VPC_CONNECTOR \
            --service-account $SERVICE_ACCOUNT_MAIL \
            --ingress=internal \
            --memory=512Mi \
            --cpu=0.1 \
            --timeout=300s \
            --max-instances=2 \
            --min-instances=1 \
            --quiet