name: Deploy Firestore in us-central1

on:
  workflow_dispatch:

jobs:
  deploy-firestore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Create Firestore (Native mode, us-central1)
        run: |
          gcloud firestore databases create \
            --location=us-central1 \
            --database=default \
            --type=firestore-native || echo "Firestore already exists"

      - name: Describe Firestore Database
        run: |
          gcloud firestore databases describe --database=default
