name: Deploy nodepool-resize Pub/Sub Push Configuration

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: extended-web-339507
      REGION: us-central1
      SERVICE_NAME: compute-worker
      VPC_CONNECTOR: cloudrun-connector
      REPO_NAME: test-repo
      IMAGE_NAME: compute-worker
      TOPIC_NAME: gke-schedule-maintenance
      DLT_NAME: gke-schedule-maintenance-dlt
      SUBSCRIPTION_NAME: gke-schedule-maintenance-sub
      SERVICE_ACCOUNT_ID: pubsub-push-sa
      SERVICE_ACCOUNT: pubsub-push-sa@extended-web-339507.iam.gserviceaccount.com
      CLOUD_RUN_URL: https://compute-worker-cv2gyc3c4a-uc.a.run.app/gke-schedule-maintenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Create Pub/Sub Topics, Subscription, and IAM
        run: |

          # 1. Create DLQ topic
          gcloud pubsub topics create $DLT_NAME --project=$PROJECT_ID || true

          # 2. Create main topic
          gcloud pubsub topics create $TOPIC_NAME --project=$PROJECT_ID || true

          # 3. Create service account for Pub/Sub push
          gcloud iam service-accounts create pubsub-push-sa \
            --display-name="Pub/Sub Push SA" \
            --project=$PROJECT_ID || true

          # 4. Add Cloud Run Invoker role
          gcloud run services add-iam-policy-binding $SERVICE_NAME \
            --member="serviceAccount:$SERVICE_ACCOUNT" \
            --role="roles/run.invoker" \
            --region=$REGION \
            --project=$PROJECT_ID || true

          # 5. Get Cloud Run URL
          CLOUD_RUN_URL=$(gcloud run services describe $SERVICE_NAME \
            --region=$REGION \
            --project=$PROJECT_ID \
            --format="value(status.url)")

          echo "Cloud Run URL: $CLOUD_RUN_URL"

          # 6. Create push subscription with DLQ
          gcloud pubsub subscriptions create $SUBSCRIPTION_NAME \
            --topic=$TOPIC_NAME \
            --push-endpoint=$CLOUD_RUN_URL \
            --push-auth-service-account=$SERVICE_ACCOUNT \
            --dead-letter-topic=projects/$PROJECT_ID/topics/$DLT_NAME \
            --max-delivery-attempts=5 \
            --ack-deadline=10 \
            --project=$PROJECT_ID || true
