name: Setup Pub/Sub Push with DLQ

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Configure Pub/Sub and Push Subscription
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Create Pub/Sub Topics, Subscription, and IAM
        run: |
          set -e

          PROJECT_ID="extended-web-339507"
          REGION="us-central1"
          TOPIC_NAME="vm-operations"
          DLT_NAME="vm-operations-dlt"
          SUBSCRIPTION_NAME="vm-operations-sub"
          SERVICE_NAME="compute-worker"
          SERVICE_ACCOUNT="pubsub-push-sa@${PROJECT_ID}.iam.gserviceaccount.com"

          # 1. Create DLQ topic
          gcloud pubsub topics create $DLT_NAME --project=$PROJECT_ID || true

          # 2. Create main topic
          gcloud pubsub topics create $TOPIC_NAME --project=$PROJECT_ID || true

          # 3. Create service account for Pub/Sub push
          gcloud iam service-accounts create pubsub-push-sa \
            --display-name="Pub/Sub Push SA" \
            --project=$PROJECT_ID || true

          # 4. Add Cloud Run Invoker role
          gcloud run services add-iam-policy-binding $SERVICE_NAME \
            --member="serviceAccount:$SERVICE_ACCOUNT" \
            --role="roles/run.invoker" \
            --region=$REGION \
            --project=$PROJECT_ID || true

          # 5. Get Cloud Run URL
          CLOUD_RUN_URL=$(gcloud run services describe $SERVICE_NAME \
            --region=$REGION \
            --project=$PROJECT_ID \
            --format="value(status.url)")

          echo "Cloud Run URL: $CLOUD_RUN_URL"

          # 6. Create push subscription with DLQ
          gcloud pubsub subscriptions create $SUBSCRIPTION_NAME \
            --topic=$TOPIC_NAME \
            --push-endpoint=$CLOUD_RUN_URL \
            --push-auth-service-account=$SERVICE_ACCOUNT \
            --dead-letter-topic=projects/$PROJECT_ID/topics/$DLT_NAME \
            --max-delivery-attempts=5 \
            --ack-deadline=10 \
            --project=$PROJECT_ID || true
